const ENDPOINT='https://harvest-viala-trigger.niya-tsukushi.workers.dev';
const esc=(v='')=>String(v).replace(/[&<>\'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const yen=n=>Number.isFinite(n)?new Intl.NumberFormat('ja-JP',{style:'currency',currency:'JPY',maximumFractionDigits:0}).format(n):'—';
const statusBox=document.getElementById('actionStatus');
const progressBox=document.getElementById('progressBox');
const progressDetail=document.getElementById('progressDetail');
const completeDialog=document.getElementById('completeDialog');
let allSlots=[];let activeView='stays';let activeFilter='all';let activeRoomFilter='all';let activeFacility='all';let activeRoom='all';let activeMinNights=2;let activePrice='all';let currentUpdatedAt='';
const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
function showStatus(message,error=false){statusBox.textContent=message;statusBox.className=error?'status error':'status';statusBox.style.display='block'}
function setProgress(active,detail=''){progressBox.classList.toggle('active',active);if(detail)progressDetail.textContent=detail}
function matchesTicketFilter(slot){const available=Array.isArray(slot.usableTickets)?slot.usableTickets:[];if(activeFilter==='home')return available.some(x=>x.includes('ホーム券'));if(activeFilter==='mutual')return available.some(x=>x.includes('相互利用券'));return true}
function matchesPetFilter(slot){if(activeRoomFilter==='pet')return slot.pet===true;if(activeRoomFilter==='regular')return slot.pet!==true;return true}
function matchesPrice(slot){const price=Number(slot.mutualPriceYen);if(activePrice==='all')return true;if(!Number.isFinite(price))return false;if(activePrice==='0-20000')return price<=20000;if(activePrice==='20001-30000')return price>=20001&&price<=30000;if(activePrice==='30001-40000')return price>=30001&&price<=40000;if(activePrice==='40001-max')return price>=40001;return true}
function baseFiltered(){return allSlots.filter(x=>matchesTicketFilter(x)&&matchesPetFilter(x)&&matchesPrice(x))}
function renderFacilityTabs(){const facilities=[...new Set(baseFiltered().map(x=>x.facility).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'ja'));if(activeFacility!=='all'&&!facilities.includes(activeFacility)){activeFacility='all';activeRoom='all'}facilityTabs.innerHTML=[`<button class="tab-button ${activeFacility==='all'?'active':''}" type="button" data-facility="all">すべて</button>`,...facilities.map(f=>`<button class="tab-button ${activeFacility===f?'active':''}" type="button" data-facility="${esc(f)}">${esc(f)}</button>`)].join('');facilityTabs.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>{activeFacility=b.dataset.facility;activeRoom='all';renderAll()}))}
function renderRoomTabs(){const source=baseFiltered().filter(x=>activeFacility==='all'||x.facility===activeFacility);const rooms=[...new Set(source.map(x=>x.room).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'ja'));if(activeRoom!=='all'&&!rooms.includes(activeRoom))activeRoom='all';roomTabs.innerHTML=[`<button class="tab-button ${activeRoom==='all'?'active':''}" type="button" data-room="all">すべて</button>`,...rooms.map(r=>`<button class="tab-button ${activeRoom===r?'active':''}" type="button" data-room="${esc(r)}">${esc(r)}</button>`)].join('');roomTabs.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>{activeRoom=b.dataset.room;renderResults()}))}
function selectedSlots(){return baseFiltered().filter(x=>(activeFacility==='all'||x.facility===activeFacility)&&(activeRoom==='all'||x.room===activeRoom))}
function dateNumber(iso){const ms=Date.parse(`${iso}T00:00:00Z`);return Number.isFinite(ms)?Math.floor(ms/86400000):null}
function commonTickets(slots){if(!slots.length)return[];let common=new Set(Array.isArray(slots[0].usableTickets)?slots[0].usableTickets:[]);for(const slot of slots.slice(1)){const next=new Set(Array.isArray(slot.usableTickets)?slot.usableTickets:[]);common=new Set([...common].filter(x=>next.has(x)))}return [...common]}
function roomKey(slot){return [slot.facility,slot.room,slot.pet===true?'pet':'regular',slot.standardCapacity??'',slot.maxCapacity??'',slot.areaSqm??''].join('\u0001')}
function buildStayRuns(slots){const groups=new Map();for(const slot of slots){const key=roomKey(slot);if(!groups.has(key))groups.set(key,[]);groups.get(key).push(slot)}const runs=[];for(const group of groups.values()){group.sort((a,b)=>a.date.localeCompare(b.date));let current=[];for(const slot of group){if(!current.length){current=[slot];continue}const previous=current[current.length-1];const consecutive=dateNumber(slot.date)===dateNumber(previous.date)+1;const candidate=[...current,slot];const ticketCompatible=activeFilter!=='all'||commonTickets(candidate).length>0;if(consecutive&&ticketCompatible){current.push(slot)}else{if(current.length>=activeMinNights)runs.push(makeRun(current));current=[slot]}}if(current.length>=activeMinNights)runs.push(makeRun(current))}return runs.sort((a,b)=>b.nights-a.nights||a.start.localeCompare(b.start)||a.facility.localeCompare(b.facility,'ja')||a.room.localeCompare(b.room,'ja'))}
function makeRun(slots){const prices=slots.map(x=>Number(x.mutualPriceYen)).filter(Number.isFinite);return{facility:slots[0].facility,room:slots[0].room,pet:slots[0].pet===true,standardCapacity:slots[0].standardCapacity,maxCapacity:slots[0].maxCapacity,areaSqm:slots[0].areaSqm,start:slots[0].date,end:slots.at(-1).date,nights:slots.length,slots,commonTickets:commonTickets(slots),minPrice:prices.length?Math.min(...prices):null,maxPrice:prices.length?Math.max(...prices):null,totalPrice:prices.length===slots.length?prices.reduce((a,b)=>a+b,0):null}}
function formatDate(iso){const d=new Date(`${iso}T00:00:00+09:00`);return new Intl.DateTimeFormat('ja-JP',{month:'numeric',day:'numeric',weekday:'short'}).format(d)}
function renderList(slots){countLabel.textContent='表示中の空室';count.textContent=`${slots.length}件`;listTitle.textContent='空室一覧';resultNote.textContent='公開データの空室を1日・1部屋ずつ表示しています。';if(!slots.length){results.innerHTML='<div class="empty"><strong>条件に合う空室はありません</strong><p>施設・部屋タイプ・券・料金の条件を切り替えてください。</p></div>';return}results.innerHTML=slots.map(x=>{const chips=(x.usableTickets||[]).map(t=>`<span class="ticket-chip">${esc(t)}</span>`).join('');return `<article class="slot"><div class="slot-head"><h3>${x.pet?'🐶 ':''}${esc(x.facility)}｜${esc(x.date)}</h3><span class="badge">${x.status==='few'?'残りわずか':'空室'}</span></div><div class="ticket-badges">${chips}</div><ul class="details"><li>部屋：<b>${esc(x.room)}</b></li><li>相互利用料金：<b>${yen(x.mutualPriceYen)}</b></li><li>定員：標準${esc(x.standardCapacity??'—')}名／最大${esc(x.maxCapacity??'—')}名${x.areaSqm?`・${esc(x.areaSqm)}㎡`:''}</li><li>判定：${esc(x.notes||'通常日')}</li></ul></article>`}).join('')}
function renderStays(slots){const runs=buildStayRuns(slots);countLabel.textContent='表示中の連泊候補';count.textContent=`${runs.length}件`;listTitle.textContent=`${activeMinNights}連泊以上できる空室`;resultNote.textContent='同じ施設・同じ部屋タイプで、日付が連続し、選択した券で通して予約可能な候補だけをまとめています。';if(!runs.length){results.innerHTML='<div class="empty"><strong>条件に合う連泊候補はありません</strong><p>必要な連泊数・施設・部屋タイプ・券・料金を切り替えてください。</p></div>';return}results.innerHTML=`<div class="stay-list">${runs.map(run=>{const chips=run.commonTickets.map(t=>`<span class="ticket-chip">${esc(t)}</span>`).join('');const nights=run.slots.map(x=>`<div class="night"><strong>${esc(formatDate(x.date))}</strong><span class="state">${x.status==='few'?'△ 残りわずか':'○ 空室'}</span><span>${yen(x.mutualPriceYen)}</span></div>`).join('');const rangePrice=run.minPrice===run.maxPrice?yen(run.minPrice):`${yen(run.minPrice)}〜${yen(run.maxPrice)}`;return `<article class="stay-card"><div class="stay-head"><div><h3>${run.pet?'🐶 ':''}${esc(run.facility)}</h3><div>${esc(run.room)}</div></div><span class="badge long">${run.nights}連泊可</span></div><div class="stay-range">${esc(formatDate(run.start))}〜${esc(formatDate(run.end))}</div><div class="stay-meta"><span>標準${esc(run.standardCapacity??'—')}名／最大${esc(run.maxCapacity??'—')}名</span>${run.areaSqm?`<span>${esc(run.areaSqm)}㎡</span>`:''}</div><div class="ticket-badges">${chips}</div><div class="night-grid">${nights}</div><div class="price-summary">1泊あたり <b>${rangePrice}</b>${Number.isFinite(run.totalPrice)?` ／ ${run.nights}泊合計目安 <b>${yen(run.totalPrice)}</b>`:''}</div></article>`}).join('')}</div>`}
function renderResults(){const slots=selectedSlots();if(activeView==='stays')renderStays(slots);else renderList(slots)}
function renderAll(){renderFacilityTabs();renderRoomTabs();renderResults();document.querySelectorAll('.ticket-filter').forEach(b=>{const a=b.dataset.filter===activeFilter;b.classList.toggle('active',a);b.setAttribute('aria-pressed',String(a))});document.querySelectorAll('.room-filter').forEach(b=>{const a=b.dataset.roomFilter===activeRoomFilter;b.classList.toggle('active',a);b.setAttribute('aria-pressed',String(a))});document.querySelectorAll('.view-button').forEach(b=>{const a=b.dataset.view===activeView;b.classList.toggle('active',a);b.setAttribute('aria-selected',String(a))});document.getElementById('minNights').disabled=activeView!=='stays'}
async function fetchData(){const r=await fetch(`./data.json?t=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json()}
async function loadData(){const data=await fetchData();allSlots=Array.isArray(data.slots)?data.slots:[];currentUpdatedAt=data.updatedAt||'';updated.textContent=currentUpdatedAt||'不明';renderAll()}
async function waitForPublishedUpdate(previousUpdatedAt){const started=Date.now();const timeout=10*60*1000;while(Date.now()-started<timeout){await sleep(10000);const elapsed=Math.floor((Date.now()-started)/1000);setProgress(true,`公開データの更新を確認中です（${elapsed}秒経過）`);try{const data=await fetchData();if(data.updatedAt&&data.updatedAt!==previousUpdatedAt)return data}catch(e){}}throw new Error('10分以内に新しいデータを確認できませんでした。')}
loadData().catch(e=>{results.innerHTML=`<div class="status error" style="display:block">データを読み込めませんでした：${esc(e.message)}</div>`;updated.textContent='取得失敗'});
document.querySelectorAll('.view-button').forEach(b=>b.addEventListener('click',()=>{activeView=b.dataset.view;renderAll()}));
document.querySelectorAll('.ticket-filter').forEach(b=>b.addEventListener('click',()=>{activeFilter=b.dataset.filter;activeFacility='all';activeRoom='all';renderAll()}));
document.querySelectorAll('.room-filter').forEach(b=>b.addEventListener('click',()=>{activeRoomFilter=b.dataset.roomFilter;activeFacility='all';activeRoom='all';renderAll()}));
document.getElementById('minNights').addEventListener('change',e=>{activeMinNights=Number(e.target.value)||2;renderResults()});
document.getElementById('priceRange').addEventListener('change',e=>{activePrice=e.target.value;activeFacility='all';activeRoom='all';renderAll()});
document.getElementById('reload').addEventListener('click',()=>location.reload());
document.getElementById('completeOk').addEventListener('click',()=>location.reload());
document.getElementById('refresh').addEventListener('click',async()=>{let key=sessionStorage.getItem('harvestRefreshKey');if(!key){key=prompt('更新用の合言葉を入力してください');if(!key)return;sessionStorage.setItem('harvestRefreshKey',key)}const button=document.getElementById('refresh');button.disabled=true;statusBox.style.display='none';setProgress(true,'GitHub Actionsを起動しています…');try{const before=currentUpdatedAt;const r=await fetch(ENDPOINT,{method:'POST',headers:{'x-refresh-key':key}});const body=await r.json().catch(()=>({}));if(!r.ok)throw new Error(body.error||`HTTP ${r.status}`);setProgress(true,'空室データを取得しています…');const data=await waitForPublishedUpdate(before);setProgress(false);document.getElementById('completeMessage').textContent=`最新データ（${data.updatedAt}）を取得しました。`;completeDialog.showModal()}catch(e){setProgress(false);sessionStorage.removeItem('harvestRefreshKey');showStatus(`取得できませんでした：${e.message}`,true)}finally{button.disabled=false}});